---
# - hosts: "app_north_virginia_lex_dev"
- hosts: "{{ deploy_host_name }}"
  become: yes
  strategy: free
  vars_files:
    - "vars/main.yml"
  roles:
    - role: stack-proxy
      tags: [stack-proxy]
    - role: deploy-esamwad-backend
      tags: [deploy-esamwad-backend]
    - role: deploy-user-service
      tags: [deploy-user-service]
    - role: deploy-fusion-auth
      tags: [deploy-fusion-auth]
    - role: deploy-yaus-hasura
      tags: [deploy-yaus-hasura]
    - role: deploy-yaus-broker
      tags: [deploy-yaus-broker]
    - role: deploy-yaus-redis-ui
      tags: [deploy-yaus-redis-ui]
    - role: deploy-yaus-web
      tags: [deploy-yaus-web]
    - role: deploy-odk-uci-adapter
      tags: [deploy-odk-uci-adapter]
    - role: deploy-odk
      tags: [deploy-odk]
    - role: deploy-doc-generator
      tags: [deploy-doc-generator]
    - role: deploy-fa-relay
      tags: [deploy-fa-relay]
    - role: deploy-fa-proxy
      tags: [deploy-fa-proxy]
