---
# - hosts: "app_north_virginia_lex_dev"
- hosts: "{{ deploy_host_name }}"
  become: yes
  strategy: free
  vars_files:
    - "vars/main.yml"
  roles:
    - role: stack-proxy
      tags: [stack-proxy]
    - role: deploy-esamwad-backend
      tags: [deploy-esamwad-backend]
    - role: deploy-user-service
      tags: [deploy-user-service]
    - role: deploy-fusion-auth
      tags: [deploy-fusion-auth]
    - role: deploy-odk-uci-adapter
      tags: [deploy-odk-uci-adapter]
    - role: deploy-odk
      tags: [deploy-odk]
    - role: deploy-fa-captcha-service
      tags: [deploy-fa-captcha-service]
